### ISSUE TITLE
First Reactions

### ISSUE THREAD

**Issue by tomdale** [linkedin/css-blocks#1]
Chris, I'm so so so excited to be working on this with you. So much time has been focused on the JavaScript side of reusable, fast components and CSS remains such a pain point for people (both ergonomically and from a performance perspective).

I wanted to write down my first impressions while I'm still more or less Curse of Knowledge-free. Hopefully documenting the delta between what I was expecting and the initial proposal will be helpful, even if we decide that the first spike is the correct one, because we can better anticipate the objections _other_ people might have.

I think, fundamentally, I was expecting something more "component-oriented." That is probably largely driven by my own biases, having been thinking about React and Glimmer components so much recently. You've been thinking about BEM a lot, so it's no wonder this proposal is framed from that perspective.

I wonder if there's some way we can join these two worlds. The proposal as-is is fairly standalone, in the sense that it introduces its own terminology and concepts. That's a win if the current excitement around components ends up being a fad (two-way bindings, anyone?). But my gut feeling is that it is here to stay, and even folks who don't write a lot of JavaScript will be thinking more in terms of components in the future thanks to Web Components, shadow DOM, etc.

Looking at the `form.block.scss` example, there's more cognitive overhead around naming than I think is necessary if we can integrate deeply into e.g. the Glimmer component model.

## Blocks & Components

If I understand correctly, it seems like there's a pretty natural correlation between a "block" and a "component". It would be nice if we could omit having to declare and name the block and have `.scss` files co-located with the component implicitly be scoped to the component block.

You still need some way to declare rules for the "component block," and there is some prior art we can consider borrowing. For example, `ember-component-css` uses the SCSS `&` parent selector. This could look like:

```css
/* src/ui/components/my-form/style.scss */
& {
  margin: 2em 0;
  padding: 1em 0.5em;

  &:state(compact) {
    margin: 0.5em 0;
    padding: 0.5em 0.5em;
  }
}
```

We could also theoretically use `:component` pseudo-selector?

Behind the scenes, this could generate a block with the same name as the component, and we could apply that class to the component automatically.

## Auto-Inferring Elements

Can we treat class names in a component template as implicit elements? Using more complex selectors would be a build error unless there was an explicit opt out.

(And can we talk about how confusing re-using the term Element is in BEM?)

## Glimmer Example

Spitballing here, but here's an strawman that's integrated into a Glimmer component.

#### Style
```scss
/* src/ui/components/sailfish-form/style.scss */
:component {
  margin: 2em 0;
  padding: 1em 0.5em;
  &:state-set(theme) {
    &:state(red) {
      color: #c00;
    }
    &:state(blue) {
      color: #006;
    }
  }

  &:state(compact) {
    margin: 0.5em 0;
    padding: 0.5em 0.5em;
  }
}

.input-area {
  display: flex;
  margin: 1em 0;
  font-size: 1.5rem;
  :state(compact) & {
    margin: 0.25em 0;
  }
}

.label {
  flex: 1fr;
}

.input {
  flex: 3fr;
  :state(theme red) & {
    border-color: #c00;
  }
  :state(theme blue) & {
    border-color: #006;
  }
}

.submit {
  width: 200px;
  &:substate(disabled) {
    color: gray;
  }
}
```

#### Template
```handlebars
{{! src/ui/components/sailfish-form/template.hbs }}
<form class="{{state 'compact'}} {{state 'theme' theme}}">
  <div class="input-area">
    <label class="label">Username</label>
    <input class="input">
  </div>
  <submit class="submit {{state disabled}}">
</form>
```

#### Component
```typescript
// src/ui/components/sailfish-form/component.ts
import Component from '@glimmer/component';

export default class extends Component {
  disabled = true;

  get theme() {
    return this.args.user.isAdmin ? 'red' : 'blue';
  }
}
```

#### Output
This is what would be rendered in the final CSS output/to the DOM (non-compressed). (Block name is inferred from component name.)

```html
<form class="sailfish-form sailfish-form--compact sailfish-form--theme-red">
  <div class="sailfish-form__input-area">
    <label class="sailfish-form__label">Username</label>
    <input class="sailfish-form__input">
  </div> 
  <submit class="sailfish-form__submit sailfish-form__submit--disabled">
</form>
```

```css
.sailfish-form { margin: 2em 0; padding: 1em 0.5em; }
.sailfish-form--theme-red { color: #c00; }
.sailfish-form--theme-blue { color: #006; }
.sailfish-form--compact { margin: 0.5em 0; padding: 0.5em 0.5em; }

.sailfish-form__input-area { display: flex; margin: 1em 0; font-size: 1.5rem; }
.sailfish-form--compact .form__input-area { margin: 0.25em 0; }

.sailfish-form__label { flex: 1fr; }

.sailfish-form__input { flex: 3fr; }
.sailfish-form--theme-red .form__input { border-color: #c00; }
.sailfish-form--theme-blue .form__input { border-color: #006; }

.sailfish-form__submit { width: 200px; }
.sailfish-form__submit--disabled { color: gray; }
```

### Discussion

A few notes about this:

1. Use `:component` to target root component block.
2. It seems like states can either be boolean or string values. I'm not sure how that interacts with the `state-set` stuff.
3. The class name for the root component block is auto-generated based on the component name, and added on the template's root element by default.
4. Any class inside the component's SCSS file is interpreted as an element. That means any combination of class names will throw an error at build time (if I understand elements correctly).
5. State goes through the `{{state}}` helper. In this example, it auto-infers the element/block to apply the state/substate to, although I don't know how reliable this would be in practice. Probably easier for the root component block than elements inside. The helper can take either a static value or dynamic data from the template.

WDYT?
