### ISSUE TITLE
Resolve transitive inheritance conflicts

### ISSUE THREAD

**Issue by chriseppstein** [linkedin/css-blocks#100]
### Input

```css
/* base.block.css */
:scope { width: 100%;   color: red; }
```

```css
/* sub.block.css */
@block-reference base from "./base.block.css";
:scope {
  extends: base;
  width: 80%;
}
```

```css
/* subsub.block.css */
@block-reference sub from "./sub.block.css";
:scope {
  extends: sub;
  width: 60%;
  color: blue
}
```

### Output
```css
/* base.css */
.base { width: 100%; color: red; }
```

```css
/* sub.css */
.sub {  width: 80%; }
.base.sub {  width: 80%; }
```

```css
/* subsub.css */
.sub { width: 60%; }
.base.subsub { width: 60%; } /* expected, but not generated */
.base.subsub { color: blue; } /* expected, but not generated */
.sub.subsub { width: 60%; }
```
