### ISSUE TITLE
CSS Custom Properties

### ISSUE THREAD

**Issue by Burzmalian** [linkedin/css-blocks#150]
Can we use custom properties for things like global color variables?

**Comment by amiller-gh** [comment]
Yes you can! Right now CSS Blocks' compilation and property conflict resolution will correctly handle custom props and leave them alone in the final build 👍 Because the guarantee of CSS Blocks / OptiCSS is, at the end of the day, our built css output will preserve the cascade, custom properties used in your application will #justwork.

CSS Blocks does not currently have a concept of a "reset" stylesheet where you can declare global, app-wide styles, but you can easily concatenate another stylesheet with Blocks' output at the end of your build to the same effect. This is actually exactly what we do with the [CSS Blocks website](https://github.com/linkedin/css-blocks/tree/master/packages/%40css-blocks/website), where we deliver global color variables. Just try to keep the specificity of these selectors below single class name specificity to avoid unexpected behavior. We may want to consider adding more robust support for this kind of pattern...

We have begun discussing what the expected behavior of custom properties are once enable Block files to be delivered / imported from `node_modules` over in this ticket: https://github.com/linkedin/css-blocks/issues/46. We've been toying with the idea of "application scopes" where we would ensure custom properties will not leak out of, but it is still in an early design phase and will probably be developed in tandem with our `node_modules` strategy. I think we want to get a write up of the proposal posted here soon (right @chriseppstein?)

**Comment by dbbk** [comment]
Just a point on the scoping of Custom Properties, we have private npm packages for shared UI components across our applications for things such as buttons, and their colours are determined by the app-level branding Custom Properties. So, we would definitely need a way to opt out of scoping!

**Comment by seaneking** [comment]
Just another :-1: against automatic scoping of custom props. IMO the biggest use case for them is global shared constants like colors, typography, etc. Transforming them and requiring  opt-out for that
use seems the wrong way around. Componnt level vars are a DX thing, and could be covered more securely with a custom construct or postcss plugin or something if you don't want to worry about explicit naming conflicts

**Comment by chriseppstein** [comment]
We won't make it hard to use css custom properties that are intended to be shared for use across components. But we do want to make it hard for custom properties to conflict unintentionally.

I'd love to hear some ideas for how we can meet both of those competing requirements without making it onerous to do either one. My general sense is that making custom properties private by default is the right thing to do, and that when they are exposed (probably via `@block-global`), they should be referenced to a source definition so that there's a dependency graph that tells us that two custom properties are the same. CSS Blocks and OptiCSS can then work together to optimize those identifiers, and ensure that conflicts are well considered.

Since custom properties can be set by JS, we'd also need a way to make sure such properties weren't mangled.

But, I'll be honest, I don't see this as a high priority item. It's unlikely to be a feature we have when 1.0 launches.

**Comment by seaneking** [comment]
Agree with @dbbk. Custom properties are global by nature, and I would much much prefer to have some kind of opt-in scoping mechanism for when/if I want to ensure that they are private (again I don't see many use cases for this, that something like a postcss plugin couldn't handle just as well).

This really feels like something that CSS blocks shouldnt be interfering with, and just let me as the author deal with. Otherwise I can see custom props being a pain to use with CSS blocks for no real gain.

**Comment by chriseppstein** [comment]
I agree that the primary use case for custom properties is for sharing values across components. A couple points:

1. A CSS Block is not isolated to a single component. Blocks are intended to be re-used across components. In this way, the isolation boundary of a block is in the dimension of a design concept, not a functional concept. A component has it's own design concepts so there is usually going to be a single block for each component, but also, there should be blocks that are shared and reused. One of the ways those blocks are reused is by letting sub-components reference classes and states of those classes within the document subtree where the root of that block was first assigned. Because custom properties are inherited in that same context, creating isolation of a custom property within a block may not be as onerous or useless as you are imagining.
2. A core use case for CSS Blocks is to allow large teams to avoid stepping on each others toes and to allow for the safe distribution of styles from a style library (E.g. a design system) to applications. CSS Blocks creates isolation of class names which ultimately reside in the global scope. I think everyone agrees this is a good idea. The same risk of custom properties colliding in the global namespace exists. Because custom properties inherit, CSS Blocks won't be able to detect collisions and force a resolution via same-element assignment. But we can still create a namespace so that referencing a custom property is unambiguous -- this would be no more inconvenient than referencing a global state from another block.

I think a code example may elucidate this (I'm spitballing here):

```css
// themes.block.css
// expose a custom property for setting and referencing in other blocks.
@block-global var(--theme-icon);

// declaring a custom property as external would signal that it's set via js or
// a non-block stylesheet and cause it to be left alone. This would mark that
// property as global as well.
@external var(--theme-color);

:scope[state|theme=blue] {
  --primary-color: lightblue;
  --highlight-color: blue;
  --icon: url(https://ourapp.com/icons/bluetheme.png);
}

.element[state|bg] {
  background-color: var(--color);
}

.icon {
  background-image: var(--icon);
}
```

```css
// my-component.block.css
@block-reference themes from "./themes.block.css";

// this demonstrates how you'd reference a custom property from outside a block
themes[state|theme=blue] :scope {
  // the selector scope in this case seems sufficient to scope the variable having been
  // assigned in scoped selector. The variable would be validated against locally defined
  // variables and those defined as global in the referenced blocks.
  // in this way, the best we can do is give an error if several blocks expose the same
  // variable as global.
  border-color: var(--color); 
}
// There needs to be a way to override a variable
themes[state|theme=blue] :scope {
  // by default you'd be setting the variable exposed as global in a referenced block.
  // if that var is removed or there's a typo, this would be come a block-scoped variable.
  --icon: url(https://ourapp.com/premium-icons/bluetheme.png);
  // this syntax is scoped so we'd be able to validate it exists but it's illegal syntax so probably a non-starter
  --themes.icon: url(https://ourapp.com/premium-icons/bluetheme.png);
}
```

```jsx
// my-component.jsx
import objstr from "obj-str";
import styles from "./my-component.block.css"
import themes from "./themes.block.css";

function myComponent(props) {
  let rootStyles = objstr({
    [styles]: true,
    [themes.element]: true,
    [themes.element.bg()]: true,
  });
  return <div className={rootStyles}>
    <div className="themes.icon">
  </div>;
}
```

I think the above code allows variables to be scoped and predictable, it doesn't make variables work differently, but allows css-blocks and opticss to work together to prevent accidental collisions as well as give errors where collisions are detected and cannot be resolved otherwise.
