### ISSUE TITLE
Restrict ClassState Styles to Elements With Base Class

### ISSUE THREAD

**Issue by amiller-gh** [linkedin/css-blocks#23]
## Problem
Currently, ClassStates may be applied to elements that do not have their corresponding class styles applied.
```scss
// .block__class
.class {
  color: red;
}
 // .block__secondary--filled
.class[state|filled] {
  background: blue;
}
```
```jsx
import block from "filename.block.css";
let styles = objstr({
  [block.secondary]: false,
  [block.secondary.filled()]: true
});
<div class={styles}></div> // Receives blue background, no color.
```

## Proposed Solution
In lieu of a runtime, or very complex static analysis, we can slightly modify ClassState output to restrict styles to elements with the corresponding parent class:
```scss
// .block__class
.class {
  color: red;
}
 // .block__class.block__class--filled
.class[state|filled] {
  background: blue;
}
```
```jsx
import block from "filename.block.css";
let styles = objstr({
  [block.secondary]: false,
  [block.secondary.filled()]: true
});
<div class={styles}></div> // Receives no styling.
```
This has the additional benefit of maintaining the specificity of pre-transformed block code, avoiding potentially confusing specificity errors.

## Potential Drawbacks
This will result in increased pre-optimized file size and may create new considerations for optimization. Discussion needed.
