### ISSUE TITLE
Public Block Classes and States

### ISSUE THREAD

**Issue by chriseppstein** [linkedin/css-blocks#311]
Currently, the output classes from blocks, classes and states are protected in the sense that you cannot address them except as a block reference expression which can be statically analyzed. The output is intentionally opaque and there's no guarantees that the classname won't change across builds (In fact, the `BEM_UNIQUE` output strategy does this on purpose to prevent developers from mistakenly believing that the classnames are stable.)

However, for adopting CSS Blocks, there are situations where a block is being ported from BEM or another convention and we need to support existing classes that are considered part of the public interface.

To support this, we will introduce a feature that allows a public classname to be aliased to a block's scope, class, or a state.

```css
/* nav.block.css */
:scope {
  block-name: navigation;
  block-alias: navigation;
  display: flex;
  flex-direction: row;
}

:scope[state|expanded] {
  block-alias: navigation--expanded;
}

.item {
  block-alias: navigation__item;
}

.item[state|size="1"] {
  block-alias: navigation__item--size-1;
}
```

Public aliases are not statically analyzed, it is assumed they are used by code that is not rewritten by css-blocks.

If the alias for a style is the same class name as would be generated for that style, it is not an error. The result should be that the class name would not be rewritten.

If a style for any block would emit the same classname as an alias that is not for that style, that style should emit a different classname as its protected classname.

If template is being analyzed and rewritten using CSS Blocks, it must use the template syntax for referencing a block style, aliases are not allowed.

`block-alias` should allow a space separated list of aliases to be provided, not just a single value as is seen above. The values can be quoted and might contain e

It is not an error for more than one block style to share classname(s) among their aliases.

Implementation notes:

* This behavior should be added to the `Style` base class for block styles.  I'd expect a `addClassAlias(name: string)` and `getClassAliases(): Set<string>`
* The `cssClasses` method of `Style` should enumerate the class aliases for all styles it enumerates and add them to the list. This method should be updated to return a `Set<string>` instead of `Array<string>`.
* A `Block` should provide a method `getAllClassnameAliases(shallow?: boolean): Set<string>` that calls `this.all(shallow)` and enumerates `getClassAliases()`.
* The [`unionInto`](https://github.com/linkedin/opticss/blob/master/packages/%40opticss/util/src/unionInto.ts) utility function from opticss will probably be helpful.
* The block aliases for all blocks in a stylesheet should be passed to opticss so that it will not rewrite them. The template rewrite option already exists and is `{rewriteIdents: { omitIdents: { class: ["list", "of", "protected", "classnames"] } } }`.
