### ISSUE TITLE
Unnecessary property conflict error(s?).

### ISSUE THREAD

**Issue by chriseppstein** [linkedin/css-blocks#370]
```scss
// grid.block.scss
:scope {
  width: 1128px;
  box-sizing: content-box;
  padding: 0 30px;
  display: block;
  margin: auto;
  position: relative;
}
```

```scss
// header.block.scss
.content {
  display: resolve("grid"); // Feels like this should be resolved by the cascade when using composes, but acceptable for now.
  display: flex;
  height: 100%;
}

.content[width="fixed"] {
  composes: grid;
}

.content[width="full"] {
  margin: resolve("grid"); // is exclusive with .content[width="fixed"] so there's not a conflict.
  margin: 0 item-spacing(6);
}
```

**Comment by hagmandan** [comment]
Another example with box-shadow/elevations in combination with other props:
```scss
// elevation-raised.block.scss
:scope {
  box-shadow: 0 4px 12px 0 rgba(0,0,0,0.15);
}
```

and include it elsewhere, with more robustness:
```scss
// container.block.scss

@block elevation-raised from "./elevation-raised.block.scss";

// default
:scope {
  box-shadow: none;
  box-shadow: resolve("elevation-raised"); // but we need to add this resolve...
}

// - Flat (default)
:scope[elevation=flat],
:scope[elevation=default] {
  box-shadow: none;
  box-shadow: resolve("elevation-raised"); // but we need to add this resolve...
}

// - Raised (elevation)
:scope[elevation=raised] {
  composes: elevation-raised; // this is the good intended use!
}

// Combine with other props
:scope[elevation=lined][color=dark] {
  box-shadow: 0 0 0 1px #efefef;
  box-shadow: resolve("elevation-raised"); // but we need to add this resolve...
}
```
