### ISSUE TITLE
Shared State

### ISSUE THREAD

**Issue by chriseppstein** [linkedin/css-blocks#41]
I've been wondering if we should have a syntax for creating a state that is shared across all classes.

An example use case for this would be a the `gutter` and `last` states for a float-based grid block.

Using Sass, you can create mixins to simplify this process, but I'd like the block syntax to be usable without a preprocessor.

```css
/* example.block.css */
.foo {
   margin: 10px;
}

.bar {
  margin: 18px;
}

*[state|last] {
   margin-right: 0;
}
```

Would then compile to:

```css
.example__foo { margin: 10px; }
.example__bar { margin: 18px; }
.example__foo--last,
.example__bar--last { margin-right: 0; }
```

Maybe it's not common enough to warrant addressing with specialized syntax, but I thought I'd write it down for discussion at some point.
