### ISSUE TITLE
Better support progressive enhancement in Conflict Validator and Conflict Resolver

### ISSUE THREAD

**Issue by amiller-gh** [linkedin/css-blocks#69]
See: https://github.com/css-blocks/css-blocks/pull/62#discussion_r167104549

After #62 lands we should not have problems with uncaught conflicts. However, there is room for improvement with how css-blocks handles progressive enhancement and vendor prefixed property resolutions. Ex:

```css
block-a.foo {
  -webkit-transform: translateY(50%);
  transform: translateY(50%);
}

block-b.foo {
  -webkit-transform: translateX(50%);
  transform: translateX(50%);
  -webkit-transform: resolve('block-a.foo;'); /* Do we need this resolution if we're PA aware? */
  transform: resolve('block-a.foo;');
}
```
