### ISSUE TITLE
Implement Class Composition

### ISSUE THREAD

**Issue by amiller-gh** [linkedin/css-blocks#72]
We require a syntax that enables class composition between blocks, similar to SASS mixins, but without duplicating declarations. For example:

### Input:
```css
/* elevation.block.css */
.elevation-2dp {
  box-shadow: 0 1px 2px 0 rgba(0, 0, 0, .55);
}
```

```css
/* modal.block.css */
@block-reference elevation from "elevation.block.css";
.root {
  apply: "elevation.elevation-2dp";
  position: fixed;
  width: 800px;
  padding: 10px;
}
```
```hbs
{{! modal.hbs }}
<div class="modal">
```

---

### Output: 
```css
.elevation__elevation-2dp {
  box-shadow: 0 1px 2px 0 rgba(0, 0, 0, .55);
}
.modal {
  position: fixed;
  width: 800px;
  padding: 10px;
}
```
```hbs
{{! modal.hbs }}
<div class="modal elevation__elevation-2dp">
```
