### ISSUE TITLE
State namespace alias

### ISSUE THREAD

**Issue by chriseppstein** [linkedin/css-blocks#97]
The state namespace should be something that can be aliased according to dev/team preferences as an authoring convenience.

```css
@namespace s url(http://css-blocks.com/state);
:scope[s|active] { font-weight: bold; }
```

We should also allow states from a block (which are element names in selectors) to have a namespace declared:

```css
@block-reference theme|button from "design-system/button.block.scss";
@namespace s url(http://css-blocks.com/state);
:scope[s|active] { font-weight: bold; font-weight: resolve("theme|button[s|clicked]")}
```

In reference to https://github.com/css-blocks/css-blocks/issues/96, this would allow us to have a way of making a reference to a collection of blocks:

@block-reference theme|* from "design-system/all.block.scss";
